version: '3'

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=files
      - MYSQL_USER=arquisoft
    ports:
      - 9000:80
    volumes:
      - ./:/var/www/app
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    ports:
      - 6603:3306
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=files
      - MYSQL_USER=arquisoft

volumes:
  mysql_data: { driver: local }
